# Generated by Django 4.2.6 on 2023-10-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boulder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boulder_1", models.CharField(max_length=100)),
                ("boulder_2", models.CharField(max_length=100)),
                ("boulder_3", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("points", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jagd.user"
                    ),
                ),
            ],
        ),
    ]
