# Generated by Django 4.2.6 on 2023-10-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jagd", "0003_rename_user_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulder",
            name="boulder_1",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="boulder_2",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="boulder_3",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
