# Generated by Django 4.2.6 on 2023-10-31 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jagd", "0004_alter_boulder_boulder_1_alter_boulder_boulder_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("woman", "Woman"), ("man", "Man")],
                        default="man",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.BooleanField(
                        choices=[
                            ("pro", "Pro"),
                            ("amateur", "Amateur"),
                            ("u18", "u18"),
                        ],
                        default="amateur",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="CustomUser",),
    ]
