# Generated by Django 4.2.6 on 2023-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0005_userprofile_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_valid", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mode",
            field=models.CharField(
                choices=[("pro", "Pro"), ("amateur", "Amateur"), ("u18", "u18")],
                default="amateur",
                max_length=10,
            ),
        ),
    ]
