# Generated by Django 4.2.6 on 2023-11-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0006_verificationcode_alter_userprofile_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulder",
            name="boulder_10",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_11",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_12",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_13",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_14",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_15",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_16",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_17",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_18",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_19",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_20",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_21",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_22",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_23",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_24",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_25",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_26",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_27",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_28",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_29",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_30",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_31",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_32",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_33",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_34",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_35",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_36",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_37",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_38",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_39",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_4",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_40",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_5",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_6",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_7",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_8",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="boulder_9",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_1",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_10",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_11",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_12",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_13",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_14",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_15",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_16",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_17",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_18",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_19",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_2",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_20",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_21",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_22",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_23",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_24",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_25",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_26",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_27",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_28",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_29",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_3",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_30",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_31",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_32",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_33",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_34",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_35",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_36",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_37",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_38",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_39",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_4",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_40",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_5",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_6",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_7",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_8",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
        migrations.AddField(
            model_name="boulder",
            name="category_9",
            field=models.JSONField(default=["pro_woman", "pro_man"]),
        ),
    ]
