# Generated by Django 4.2.6 on 2023-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0007_boulder_boulder_10_boulder_boulder_11_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulder",
            name="category_1",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_10",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_11",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_12",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_13",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_14",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_15",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_16",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_17",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_18",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_19",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_2",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_20",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_21",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_22",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_23",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_24",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_25",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_26",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_27",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_28",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_29",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_3",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_30",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_4",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_5",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_6",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_7",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_8",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="category_9",
            field=models.JSONField(default=["amateur_woman", "amateur_man"]),
        ),
    ]
