# Generated by Django 4.2.6 on 2023-11-11 11:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0009_category_usersubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllBoulders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boulder_number", models.IntegerField(unique=True)),
                ("belonging_category", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Category",),
        migrations.AddField(
            model_name="userprofile",
            name="category",
            field=models.CharField(
                default="<django.db.models.fields.CharField>_<django.db.models.fields.CharField>",
                max_length=100,
            ),
        ),
    ]
