# Generated by Django 4.2.6 on 2023-11-11 12:05

from django.db import migrations, models

def populate_categories(apps, schema_editor):
    Category = apps.get_model('jagd', 'Category')

    initial_categories = [
        "pro_woman", "pro_man",
        "amateur_woman", "amateur_man",
        "u18_woman", "u18_man",
    ]

    for category_name in initial_categories:
        Category.objects.create(name=category_name)

def generate_boulders(apps, schema_editor):
    AllBoulders = apps.get_model('jagd', 'AllBoulders')
    Category = apps.get_model('jagd', 'Category')

    # Assuming you have already created categories
    u18_woman = Category.objects.get(name="u18_woman")
    u18_man = Category.objects.get(name="u18_man")
    amateur_woman = Category.objects.get(name="amateur_woman")
    pro_woman = Category.objects.get(name="pro_woman")
    pro_man = Category.objects.get(name="pro_man")
    amateur_man = Category.objects.get(name="amateur_man")

    # Create boulders with multiple categories
    boulder1 = AllBoulders.objects.create(boulder_number=1)
    boulder1.belonging_categories.set([u18_woman, u18_man])

    boulder2 = AllBoulders.objects.create(boulder_number=2)
    boulder2.belonging_categories.set([amateur_woman, amateur_man])

    boulder3 = AllBoulders.objects.create(boulder_number=3)
    boulder3.belonging_categories.set([pro_woman, pro_man])

    boulder4 = AllBoulders.objects.create(boulder_number=4)
    boulder4.belonging_categories.set([pro_woman, pro_man])


class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0010_allboulders_delete_category_userprofile_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="allboulders", name="belonging_category",),
        migrations.AddField(
            model_name="allboulders",
            name="belonging_categories",
            field=models.ManyToManyField(to="jagd.category"),
        ),
        migrations.RunPython(populate_categories),
        migrations.RunPython(generate_boulders),
    ]
