# Generated by Django 4.2.6 on 2023-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jagd", "0012_bjm_bjw_u18m_u18w_ue50m_ue50w_remove_boulder_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bjm", name="bonus_amount", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bjm", name="tops_amount", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bjw", name="bonus_amount", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bjw", name="tops_amount", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="u18m",
            name="bonus_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="u18m", name="tops_amount", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="u18w",
            name="bonus_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="u18w", name="tops_amount", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ue50m",
            name="bonus_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ue50m",
            name="tops_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ue50w",
            name="bonus_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ue50w",
            name="tops_amount",
            field=models.IntegerField(default=0),
        ),
    ]
